# =========================
#  Site Settings
# =========================
title: "Geoffrey Kiuna"
tagline: "CTF Writeups & Security Lab Walkthroughs"
description: "Detailed CTF writeups, penetration testing labs, and cybersecurity research."
url: "https://kiunajeff.github.io"
baseurl: ""   # leave empty for username.github.io sites

# =========================
#  Author Information
# =========================
author:
  name: "Geoffrey Kiuna"
  email: "geoffreykiuna071@gmail.com"
  github: "KiunaJeff"
  linkedin: "www.linkedin.com/in/geofreykiuna"
  twitter: "your-twitter-handle"

# =========================
#  Theme Configuration
# =========================
remote_theme: "madhathacker/cyber.blog"

# =========================
#  Plugins
# =========================
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# =========================
#  Pagination
# =========================
paginate: 5
paginate_path: "/page:num/"

# =========================
#  Navigation Links
# =========================
nav:
  - title: "Home"
    url: /
  - title: "Blog"
    url: /blog/
  - title: "Categories"
    url: /categories/
  - title: "Tags"
    url: /tags/
  - title: "About"
    url: /about/
  - title: "Portfolio"
    url: /  # points to your main portfolio page (index.html)

